baseURL = 'https://zigzagging.io'
languageCode = 'zh-CN'
title = 'Zigzagging Blog'
theme = 'hugo-modus'
copyright = '© 2026 zigzagging.io'

enableRobotsTXT = true

[params]
  description = 'Sharing my tech insights, thoughts, and lifestyle.'

[permalinks]
  posts = '/:slug/'

[markup]
  [markup.highlight]
    noClasses = false

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 100
